image:
  repository: ""
  tag: ""

service:
  port: 3000

replicaCount: 1

probes:
  liveness: /
  readiness: /

resources:
  limits:
    cpu: 800m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPU: 70
  targetMemory: 80

env: [ ]
envFrom: [ ]

externalSecrets:
  enabled: false
  secrets: [ ]

serviceAccount:
  gcpServiceAccount: ""

imagePullSecrets: []
