image:
  pullPolicy: Always

replicaCount: 2

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi
imagePullSecrets:
  - name: ghcr-secret
