imageRegistry: "ghcr.io/trip-manager-htwg"
imagePrefix: "backend/"
imageTag: "dev"
projectId: "staging-demo-502317"
neo4j:
  enabled: true
feed:
  enabled: true
newsletter:
  enabled: true
imagePullSecrets:
  - name: ghcr-secret