image:
  pullPolicy: Always

replicaCount: 1

service:
  healthPath: /health

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

hpa:
  enabled: false

env:
  - name: PORT
    value: "8083"
  - name: LOG_LEVEL
    value: "info"
  - name: AUTH_SERVICE_URL
    value: "http://auth.trip-manager-staging.svc.cluster.local:8082"
  - name: STORAGE_BUCKET_URL
    value: "https://storage.googleapis.com/staging-demo-502317-trip-manager-bucket"
  - name: CORS_ALLOWED_ORIGINS
    value: "https://staging.neatnode.xyz,https://www.staging.neatnode.xyz"
  - name: OTEL_COLLECTOR_ENDPOINT
    value: "otel-collector.trip-manager-staging.svc.cluster.local:4317"
  - name: GCP_PROJECT_ID
    value: "staging-demo-502317"
  - name: GITHUB_REPO
    value: "trip-manager-htwg/application"
  - name: GITHUB_BRANCH
    value: "main" # branch benannt bevor staging dazu kam
  - name: BASE_URL
    value: "https://staging.neatnode.xyz"

externalSecrets:
  enabled: true
  secrets:
    - secretKey: MIGRATION_DB_URL
      remoteKey: users-migration-url
    - secretKey: DATABASE_URL
      remoteKey: users-database-url
    - secretKey: APP_DB_PASSWORD
      remoteKey: users-app-database-password
    - secretKey: RESEND_API_KEY
      remoteKey: resend-api-key
    - secretKey: GITHUB_TOKEN
      remoteKey: github-token
    - secretKey: INTERNAL_SECRET
      remoteKey: internal-secret

envFrom:
  - secretRef:
      name: users-secrets

serviceAccount:
  gcpServiceAccount: "users-sa@staging-demo-502317.iam.gserviceaccount.com"
imagePullSecrets:
  - name: ghcr-secret
