image:
  repository: ""
  tag: ""
  pullPolicy: Always

service:
  port: 8089

replicaCount: 1

probes:
  liveness: /health
  readiness: /health

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 70
  targetMemory: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  - name: PORT
    value: "8089"

externalSecrets:
  enabled: false
  secrets: []

imagePullSecrets: []
