ALTER TABLE newsletters
    FORCE ROW LEVEL SECURITY;
ALTER TABLE advertiser_insights
    FORCE ROW LEVEL SECURITY;

GRANT CONNECT ON DATABASE newsletter TO newsletter_app;
GRANT USAGE ON SCHEMA public TO newsletter_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO newsletter_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO newsletter_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO newsletter_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO newsletter_app;