{{- if eq .Values.ingress.className "gke-l7-global-external-managed" }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: trip-manager-gateway
  namespace: {{ .Release.Namespace }}
  annotations:
    networking.gke.io/certmap: "{{ .Values.ingress.certMap | default "trip-manager-cert-map" }}"
    networking.gke.io/load-balancer-ip: "{{ .Values.ingress.staticIP }}"
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: Same
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
{{- end }}