imageRegistry: "ghcr.io/trip-manager-htwg"
imagePrefix: "backend/"
imageTag: "main"
projectId: "ornate-reef-501614-a1"
neo4j:
  enabled: true
feed:
  enabled: true
newsletter:
  enabled: true
imagePullSecrets:
  - name: ghcr-secret