apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trip-manager-prod
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/trip-manager-htwg/application/.git
        revision: gitops-prod
        directories:
          - path: gitops/prod/*
          - path: gitops/prod/external-secrets
            exclude: true
          - path: gitops/prod/cluster-config
            exclude: true
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/trip-manager-htwg/application/.git
        targetRevision: gitops-prod
        path: '{{path}}'
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: trip-manager-prod
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true