image:
  pullPolicy: Always

replicaCount: 2

service:
  healthPath: /health

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3

externalSecrets:
  enabled: true
  secrets:
    - secretKey: MIGRATION_DB_URL
      remoteKey: newsletter-migration-url
    - secretKey: DATABASE_URL
      remoteKey: newsletter-database-url
    - secretKey: APP_DB_PASSWORD
      remoteKey: newsletter-app-database-password
    - secretKey: USERS_DB_URL
      remoteKey: users-database-url
    - secretKey: NEO4J_URI
      remoteKey: neo4j-url
    - secretKey: NEO4J_USERNAME
      remoteKey: neo4j-username
    - secretKey: NEO4J_PASSWORD
      remoteKey: neo4j-password
    - secretKey: RESEND_API_KEY
      remoteKey: resend-api-key

envFrom:
  - secretRef:
      name: newsletter-secrets

env:
  - name: PORT
    value: "8070"
  - name: LOG_LEVEL
    value: "info"
  - name: AUTH_SERVICE_URL
    value: "http://auth.trip-manager-prod.svc.cluster.local:8082"
  - name: CORS_ALLOWED_ORIGINS
    value: "https://neatnode.xyz,https://www.neatnode.xyz"
  - name: OTEL_COLLECTOR_ENDPOINT
    value: "otel-collector.trip-manager-prod.svc.cluster.local:4317"


serviceAccount:
  gcpServiceAccount: "newsletter-sa@ornate-reef-501614-a1.iam.gserviceaccount.com"
imagePullSecrets:
  - name: ghcr-secret
