image:
  repository: ""
  tag: ""
  pullPolicy: Always

service:
  port: 8081

replicaCount: 1

probes:
  liveness: /health
  readiness: /health

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 70
  targetMemory: 80

env:
  - name: PORT
    value: "8081"
  - name: LOG_LEVEL
    value: "info"
  - name: STORAGE_PROVIDER
    value: "s3" # Default Provider, wird in Prod durch GCS überschrieben
  - name: STORAGE_TTL
    value: "15m"

envFrom: []

serviceAccount:
  gcpServiceAccount: ""

externalSecrets:
  enabled: false
  secrets: []

imagePullSecrets: []
