image:
  pullPolicy: Always

replicaCount: 1

service:
  healthPath: /health

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

hpa:
  enabled: false

env:
  - name: PORT
    value: "8081"
  - name: LOG_LEVEL
    value: "info"
  - name: FIRESTORE_PROJECT_ID
    value: "staging-demo-502317"
  - name: AUTH_CLIENT_CONNECTION_STRING
    value: "http://auth.trip-manager-staging.svc.cluster.local:8082"
  - name: USERS_SERVICE_URL
    value: "http://users.trip-manager-staging.svc.cluster.local:8083"
  - name: GCP_PROJECT_ID
    value: "staging-demo-502317"
  - name: PUBSUB_TOPIC_ID
    value: "trip-events"
  - name: CORS_ALLOWED_ORIGINS
    value: "https://staging.neatnode.xyz,https://www.staging.neatnode.xyz"
  - name: OTEL_COLLECTOR_ENDPOINT
    value: "otel-collector.trip-manager-staging.svc.cluster.local:4317"
  - name: STORAGE_PROVIDER
    value: "gcs"
  - name: STORAGE_BUCKET
    value: "staging-demo-502317-trip-manager-bucket"
  - name: AUTH_SERVICE_URL
    value: "http://auth.trip-manager-staging.svc.cluster.local:8082"
  - name: GCS_SIGNER_SA
    value: "social-sa@staging-demo-502317.iam.gserviceaccount.com"

serviceAccount:
  gcpServiceAccount: "social-sa@staging-demo-502317.iam.gserviceaccount.com"
imagePullSecrets:
  - name: ghcr-secret
