image:
  repository: ""
  tag: ""

service:
  port: 8082

replicaCount: 1

probes:
  liveness: /health
  readiness: /health

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 70
  targetMemory: 80

env:
  - name: PORT
    value: "8082"
  - name: LOG_LEVEL
    value: "info"

envFrom: []

externalSecrets:
  enabled: false
  secrets: []

serviceAccount:
  gcpServiceAccount: ""

imagePullSecrets: []
